### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by m-a-y-a-n-k** [m-a-y-a-n-k/AlgoLens#1]
Suggest the right project structure and implement it such that it is scalable based on the increasing complexity of the project.

**Comment by himanshujasuja1040** [comment]
I would like to take this up 
![image](https://user-images.githubusercontent.com/75385885/121773416-72b79200-cb99-11eb-8ff8-b173a0887bc4.png)

**Comment by m-a-y-a-n-k** [comment]
@himanshujasuja1040  Good design. Permission granted. Let's see how quickly can you build a prototype.

**Comment by himanshujasuja1040** [comment]
For Mobile Main Page : 
![image](https://user-images.githubusercontent.com/75385885/122102258-e0321f80-ce32-11eb-8d4e-a27e74fc75d4.png)

**Comment by m-a-y-a-n-k** [comment]
@himanshujasuja1040  Please file a separate issue for homepage UI discussion and discuss there

**Comment by m-a-y-a-n-k** [comment]
We have a pretty good foundation for project structure now.
