### ISSUE TITLE
Data Structure : Matrices

### ISSUE THREAD

**Issue by m-a-y-a-n-k** [m-a-y-a-n-k/AlgoLens#11]
This story is supposed to be considered complete when a site page is created for the data structure Matrix that is accessible in autocomplete search box at site header and allows following operations to the user -

1. Create an n x m 2d matrix of generic data type objects.
2. The addition of two or more compatible matrices is supported. (Nested Loop)
3. Multiplication of more than one compatible matrices is supported. (By Fast D&C and Slow 
 Three Loops methods)
4. The exponentiation of a matrix is supported (By D&C).
5. Scalar Multiplication of a single matrix is supported. (Nested Loop)
6. The Transpose operation can be applied to the matrix. (Using extra space)
7. The type of matrix can be identified (Wikipedia to know various types)
8. The determinant of the matrix can be calculated. (Recursive approach)
9. The Inverse of the matrix can be calculated if invertible.
10. The trace of a matrix can be calculated.
11. A system of linear equations can be solved by matrix method if possible.

* The working of all the above operations would be shown step by step.

**Comment by naman3112** [comment]
i will be working on this
